# www 도메인을 메인 도메인으로 리디렉션
server {
    listen 80;
    server_name www.bktheater.com;
    return 301 $scheme://bktheater.com$request_uri;
}

# 메인 도메인 설정
server {
    listen 80;
    server_name bktheater.com localhost;

    location / {
        proxy_pass http://localhost:4000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
